### ISSUE TITLE
How to implement in my project.

### ISSUE THREAD

**Issue by Louis345** [franciscop/recordar#1]
Hello,

Thank you so much for taking the time to write this plugin. Question, I am trying to implement this plugin in my current Japanese Flash Card App. My question is how do I prompt the user if they understand the word. For example, let's say they instantly recall the answer do I ask them from 1 to 5 and feed that response to your API? The due date how do I convert that what metric is that in?  I really want to use your plugin, I am just unsure on how to do so. Any clarification would be appreciated.

**Comment by franciscop** [comment]
Ah I should probably add a "deprecated" or something; now I use simpler euristics with few `ifs`, it brings much better results. The problem with this is that it works great in general, but doesn't work with specific cases:

- User failed a word; put it in the "next" list so they practice it right away
- Avoid repeating consecutive words
- Etc etc

All in all, I'd recommend **not** using this package anymore.

**Comment by franciscop** [comment]
About your questions, you rate the answer as "good" or "bad". There is no "due date", just the user's score for the current word. Then you'd choose the one with the lowest score as the next one to ask.
